### ISSUE TITLE
miniImagenet experiments

### ISSUE THREAD

**Issue by kikyou123** [dragen1860/MAML-Pytorch#16]
Hi, thanks for sharing your code, BTW, I tried with the most recent version, but I couldn't get the same results as reported, 5-way 1-shot. I could get up to ~43% accs, do you have any idea?

In addition, I want to increase the num_filter from 32 to 64, and it causes out of memory? Do you have any idea about why it takes so many memory with a four-layer network?

**Comment by dragen1860** [comment]
hi, maybe you need enlarge the default epoches. I trained it and got 46% with no modification.

Since it involves 2nd order derivative, so the gpu memory occupy is extremely demanding. Maybe you can scale the task number down to try larger channels. But on the other hand, any changes will harm the performance.

MAML is really sensitive.

**Comment by xmengli999** [comment]
I also cannot reproduce the result using the default para. 
The result for 5 way 1 shot is 42.94%. How can I address this issue.

**Comment by dragen1860** [comment]
Hi, my performance report in readme file is true. just enlarge training epoch.

**Comment by juliusyang97** [comment]
hi，The results of my running are as follows：

“Test acc: [0.2012 0.5845 0.6074 0.613  0.6143 0.6147]”

I ran the code for six hours in Tesla k80 ，miniImageNet-5-way-1-shot
